### ISSUE TITLE
Babylon cannot handle URLs with encoded endpoint

### ISSUE THREAD

**Issue by markusweigelt** [Kompakkt/Viewer#51] opened 2024-06-05 16:09 UTC
**Describe the bug**

If the viewer is called with an encoded endpoint parameter, the model is not rendered, and a misleading error message appears.

URL encoding the parameter is important to ensure that the value is correctly associated with the parameter.
In the Kompakkt Standalone Viewer, the parameter is also encoded.
https://github.com/Kompakkt/StandaloneViewer/blob/e7f34fac46f0006ebcb891a8fa7ef6810ca9c6e0/kompakkt-standalone.js#L27

In the Kompakkt Viewer sources, the URL is passed to Babylon,

https://github.com/Kompakkt/Viewer/blob/e42494ce39e14333153331abc1a35509c871e569/src/app/services/processing/processing.service.ts#L449

which then returns an error indicating that the URL cannot be found.

https://github.com/Kompakkt/Viewer/blob/e42494ce39e14333153331abc1a35509c871e569/src/app/services/processing/processing.service.ts#L458

**To Reproduce**
1. Go to 'https://kompakkt.de/viewer/index.html?standalone=true&minimal=true&endpoint=https%253A%252F%252Fzenodo.org%252Fapi%252Ffiles%252F&resource=df31cc16-0a54-4599-89e9-0dd4ada4016d%252Fb5df7cd550f64e818943ad96fff7e902.glb'
2. See error in browser console

**Workaround**
If the `endpoint` parameter is not encoded, the model will be rendered.

![image](https://github.com/Kompakkt/Viewer/assets/3832618/8d4bc5dc-d793-41d7-8231-53eae00c2396)

**Expected behavior**
The Kompakkt viewer can handle encoded endpoint parameters, and the model is renderd.

**Screenshots**
Connection to entity server to load entity refused." when using endcoded endpoints.
![image](https://github.com/Kompakkt/Viewer/assets/3832618/5169affe-14fb-46ba-9865-17e167bda05e)

**Comment by HeyItsBATMAN** [comment] 2024-06-05 18:42
Hey @markusweigelt, thanks for outlining the issue.

It should be fixed with the following PR, which I will merge and deploy shortly: https://github.com/Kompakkt/Viewer/pull/52

**Closed by HeyItsBATMAN** 2024-06-05 18:42 UTC

**Comment by HeyItsBATMAN** [comment] 2024-06-05 19:51
The fix is not deployed, and the example link you gave is now working as intended.
